version: "3.8"
services:
  backend:
    build: ./data_backend
    ports:
      - "8000:8000"
    env_file: .env
  dashboard:
    build: ./dashboard
    ports:
      - "3000:3000"
    depends_on:
      - backend
